hokuyo_spel_master_node:
  ros__parameters:
    # Published topics
    spel_cmd_topic: "/spel_cmd"
    spel_ip_address_topic: "/spel_ip_address"

    # Subscribed topics
    nav_sat_fix_topic: "/fix"
    gpgga_topic: "/gga"
    gprmc_topic: "/rmc"
    gpzda_topic: "/zda"
    hokuyo_cloud2_topic: "/hokuyo3d/hokuyo_cloud2"
    imu_topic: "/hokuyo3d/imu"
    imu_rate_odom_topic: "/hokuyo_lio/imu_rate_odom"
    nav_sat_fix_switch_topic: "/fix/switch"
    utm_odom_topic: "/odometry/utm"
    switch_odom_topic: "/odometry/switch"
    switch_odom_state_topic: "/odometry/switch/state"
    switch_odom_type_topic: "/odometry/switch/type"
    switch_fix_state_topic: "/fix/switch/state"
    switch_fix_type_topic: "/fix/switch/type"
    diagnostics_topic: "/diagnostics"
 
    # Streaming flags
    stream_nav_sat_fix: true
    stream_gpgga: true
    stream_gprmc: true
    stream_gpzda: true
    stream_hokuyo_cloud2: true
    stream_imu: true
    stream_imu_rate_odom: true
    stream_nav_sta_fix_switch: true
    stream_utm_odom: true
    stream_switch_odom: true
    stream_switch_odom_state: true
    stream_switch_odom_type: true
    stream_switch_fix_state: true
    stream_switch_fix_type: true
    stream_diagnostics: true

